spring:
  application:
    name: api-reservations


management:
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"

info:
  application:
    groupId: "@project.groupId@"
    artifactId: "@project.artifactId@"
    version: "@project.version@"


server:
  port: 8080
  servlet:
    context-path: /api
  compression:
    enabled: true
    min-response-size: 1024
    mime-types:
      - text/html
      - text/xml
      - text/plain
      - text/css
      - application/json
      - application/xml

http-connector:
  hosts:
    api-catalog:
      host: "search.reservamos.mx"
      port: 8080
      endpoints:
        get-city:
          url: "/api/v2/places?q=#{code}"
          readTimeout: 1000
          writeTimeout: 1000
          connectionTimeout: 1000

resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        sliding-window-size: 5
        sliding-window-type: COUNT_BASED
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 1

        register-health-indicator: false
        record-exceptions:
          - io.netty.handler.timeout.ReadTimeoutException
          - java.lang.RuntimeException
    instances:
      api-catalog:
        base-config: default

  rateLimiter:
    configs:
      default:
        limit-for-period: 5
        limit-refresh-period: 10s
        timeout-duration: 1s
    instances:
      post-reservation:
        base-config: default
